# default config

# 交易对配置
trading:
  symbols:
    - "BNBBTC"
  streams:
    - "bnbbtc@miniTicker"
    - "bnbbtc@bookTicker"

# 数据存储配置
storage:
  data_dir: "data/raw"
  processed_dir: "data/processed"

# 日志配置
logging:
  level: "INFO"
  file: "logs/trading.log"
